### ISSUE TITLE
Empty or outcommented file

### ISSUE THREAD

**Issue by susheelbhanu** [RasmussenLab/phamb#37]
Hi, 

I'm trying to run `PHAMB` with the following:
```bash
python /work/projects/nomis/assemblies/viromes/submodules/phamb/workflows/mag_annotation/scripts/run_RF.py /work/projects/nomis/assemblies/virome_results/annotations/goodQual_final.fna.gz /work/projects/nomis/assemblies/virome_results/vamb_output/clusters.tsv /work/projects/nomis/assemblies/virome_results/dbs/phamb /work/projects/nomis/assemblies/virome_results/phamb_output
```

I have the below error, so could you please let me know how to fix it?
```bash
Traceback (most recent call last):
  File "/work/projects/nomis/assemblies/viromes/submodules/phamb/workflows/mag_annotation/scripts/run_RF.py", line 217, in <module>
    fastadict = _vambtools.loadfasta(infile,compress=False)
  File "/mnt/irisgpfs/projects/nomis/assemblies/viromes/submodules/phamb/workflows/mag_annotation/scripts/vambtools.py", line 383, in loadfasta
    for entry in byte_iterfasta(byte_iterator, comment=comment):
  File "/mnt/irisgpfs/projects/nomis/assemblies/viromes/submodules/phamb/workflows/mag_annotation/scripts/vambtools.py", line 264, in byte_iterfasta
    raise ValueError('Empty or outcommented file')
ValueError: Empty or outcommented file
```

Thank you,
Susheel

**Comment by susheelbhanu** [comment]
Turns out I had an incomplete FASTA file. Sorry for the confusion!
