### ISSUE TITLE
'run_RF.py' operation problem 

### ISSUE THREAD

**Issue by ChaoXianSen** [RasmussenLab/phamb#55]
Dear @joacjo 

Question: Which part of the source code can I change, to fit my contigs file and Run the 'run_RF.py ' to get the final result ??

R63.contigs.fa.gz header format :   >k141_84347 flag=1 multi=9.0000 len=118435                                              
                                                          CCATAAATCTGATTTTAGTCAAAAAAATATGCAGTTTTTCAAAAAGGGTGTATAATTCTTTCGTTAC

'vae_clusters.tsv' format :   ‘vae_1   k141_84347
                                            vae_2   k141_92682
                                            vae_2   k141_551576
                                            vae_2   k141_358295’ 

run mode:  python run_RF.py \
                            R63.contigs.fa.gz \
                            vae_clusters.tsv \
                            annotations \
                            resultdir

err report : 
Traceback (most recent call last):
  File "/public/home/bioinfo_wang/00_software/phamb-v.1.0.1/phamb/run_RF.py", line 223, in <module>
    reference = run_RF_modules.Reference.from_clusters(clusters = clusters, fastadict=fastadict, minimum_contig_len=2000)
  File "/public/home/bioinfo_wang/00_software/miniconda3/envs/phamb/lib/python3.9/site-packages/phamb/run_RF_modules.py", line 272, in from_clust
    genomes = cls._parse_clusters(clusters,fastadict,minimum_contig_len=minimum_contig_len)
  File "/public/home/bioinfo_wang/00_software/miniconda3/envs/phamb/lib/python3.9/site-packages/phamb/run_RF_modules.py", line 286, in _parse_clu
    contig_len = fastadict[contig].__len__()
KeyError: 'k141_84347'

Thanks !

**Comment by ChaoXianSen** [comment]
Dear @joacjo 
you can use the following two files for testing: 
contigs file : https://drive.google.com/file/d/1s9zOQnPp9yEygeJcWNcCM2VUJJla66Ln/view?usp=sharing
BAM file : https://drive.google.com/file/d/17E8LbtzF6MJVmq5IlR8OFq3PAsGrB2k6/view?usp=sharing

Any idea about this problem? 

Looking forward to you reply ! thanks a lot !
